development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis-17498.c275.us-east-1-4.ec2.cloud.redislabs.com:17498?password= iBZATIGqTj29vDOShCQ608sS3dbvhfRH
  channel_prefix: message_me_production
